# Generated by Django 4.0.4 on 2023-06-19 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='itineraries')),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('places_to_visit', models.TextField(blank=True, max_length=10000)),
                ('places_to_eat', models.TextField(blank=True, max_length=10000)),
                ('places_to_sleep', models.TextField(blank=True, max_length=10000)),
                ('start_point', models.CharField(max_length=200)),
                ('waypoints', models.CharField(blank=True, max_length=1000)),
                ('end_point', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=100)),
                ('travel_time', models.CharField(max_length=100)),
                ('winter_stats', models.BooleanField(blank=True, default=False)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_itineraries', to='account.profile')),
                ('disliked_by', models.ManyToManyField(blank=True, related_name='disliked_itineraries', to='account.profile')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_itineraries', to='account.profile')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_itineraries', to='account.profile')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
    ]
