# Generated by Django 4.0.4 on 2023-07-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('itinerary', '0002_itinerary_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_itineraries', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_itineraries', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_itineraries', to='account.profile'),
        ),
    ]
