# Generated by Django 4.0.4 on 2023-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('itinerary', '0003_alter_itinerary_disliked_by_alter_itinerary_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_itineraries', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_itineraries', to='account.profile'),
        ),
    ]
