# Generated by Django 4.0.4 on 2023-06-19 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, choices=[(None, 'Select Country'), ('Italy', 'Italy'), ('Romania', 'Romania'), ('Switzerland', 'Switzerland'), ('Germany', 'Germany'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Slovenia', 'Slovenia'), ('Hungary', 'Hungary'), ('Croatia', 'Croatia'), ('Bulgaria', 'Bulgaria'), ('Czech Republic', 'Czech Republic'), ('Poland', 'Poland'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark')], max_length=50, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=50, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=50, verbose_name='Town')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='events')),
                ('is_public', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('participants_number', models.IntegerField(default=0)),
                ('interested_number', models.IntegerField(default=0)),
                ('participants_required', models.PositiveIntegerField(default=0)),
                ('maximal_participants', models.PositiveIntegerField(default=float("inf"))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='account.profile')),
                ('disliked_by', models.ManyToManyField(blank=True, related_name='disliked_events', to='account.profile')),
                ('interested_participants', models.ManyToManyField(blank=True, related_name='interested_participants', to='account.profile')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_events', to='account.profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='account.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.profile')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
